/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mercurio22 (https://sketchfab.com/mercurio22)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-90-premium-4b2280c16b67481cba0fe7ffacd77011
Title: Nike Air Max 90 Premium
*/

import * as THREE from 'three';
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model(props) {
  const { nodes, materials } = useGLTF('/models/nike_air_max_90_premium.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.25, 1]} scale={0.021}>
        <group rotation={[Math.PI / 2, 0.5, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base1_Base2_0.geometry}
            material={materials.Base2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base1_Logo_0.geometry}
            material={materials.Logo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base1_Cordones_0.geometry}
            material={materials.Cordones}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base1_Suela_0.geometry}
            material={materials.Suela}
          />
        </group>
      </group>
    </group>
  )
}
export default Model
useGLTF.preload('/models/nike_air_max_90_premium.glb')